import type { Metadata } from "next";
import { AuthProvider } from "@/providers/AuthProvider";
import "@/styles/globals.css";
import "@/styles/login.css";

export const metadata: Metadata = {
  title: "دستیار هوشمند آیوا",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa">
      <body>
        <div className="app-shell" dir="rtl">
          <div className="app-content">
            <AuthProvider>{children}</AuthProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
